
class MyException(Exception):
    pass

if True:
    raise MyException("Custom exception is occured")